name: Deploy to Databricks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This checks out your repository code to the GitHub Actions runner

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli  # This installs the Databricks CLI

    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}  # Your Databricks workspace URL
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}  # Your Databricks personal access token
      run: |
        echo "[DEFAULT]" > ~/.databrickscfg
        echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
        echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg  # This configures the Databricks CLI with your workspace and token

    - name: Deploy notebooks
      run: |
        databricks workspace import_dir --overwrite test /Users/siddharthkamal007@outlook.com/test 
        # The 'notebooks' is the path in your GitHub repository where your notebooks are located
        # '/Users/myuser/test' is the path in your Databricks workspace where you want to import the notebooks to
